### ISSUE TITLE
Truncated image in the synthetic dataset

### ISSUE THREAD

**Issue by naoto0804** [HCIILAB/Scene-Text-Removal#10]
Thank you for showing cool projects and providing the code!
When I download the dataset, it seems`syn_train/label/train_img_7348.png` is truncated. If possible, could you share non-truncated version?

![train_img_7348](https://user-images.githubusercontent.com/7067992/69238316-08b45200-0bdb-11ea-8a93-136a35b5fc62.png)

**Comment by zhangshuaitao** [comment]
@naoto0804, Thank you for your attention! file:///media/zst/d619af75-82b1-47c0-b0b8-2083613e7fb8/home/zst/new_EnsNET/EnsNet/train_img_7348.png

**Comment by zhangshuaitao** [comment]
@naoto0804 , Thank you for your suggestion!  
![train_img_7348](https://user-images.githubusercontent.com/30206688/69299522-ae9fa500-0c4b-11ea-8e4f-f928b5e84d5b.png)

**Comment by naoto0804** [comment]
Thank you so much!
