### ISSUE TITLE
 self.layer6 = nn.Conv2D(2,kernel_size=1)  is that a bug?

### ISSUE THREAD

**Issue by neouyghur** [HCIILAB/Scene-Text-Removal#12]
Hi, I am trying to reimplement your model. Is that a bug?  Are you sure the number of kernels is 2?  Thanks.

**Comment by zhangshuaitao** [comment]
@ neouyghur ,  2  is the number of the output channels. We hope it can implicitly learn the classification features of text and non-text

**Comment by neouyghur** [comment]
@zhangshuaitao  Thanks for the explanation. I thought it was a typo. I have successfully built the model in PyTorch. Hope I get some good results. Thanks.

**Comment by zhangshuaitao** [comment]
@You're welcome, thank you very much for your attention.

**Comment by Sanster** [comment]
@neouyghur  How do you handle layer6 and have you increased the number of out channels?
