### ISSUE TITLE
hello, when i try to train the model, it raises a shape error, is there any suggestion? thanks.

### ISSUE THREAD

**Issue by Fannjh** [HCIILAB/Scene-Text-Removal#17]
I want to try my own model, so i set the train model path to "None", and i test the train codes with the provided example dataset, but it raises the error "shape is not match", any sugguestion will be appreciated.  @zhangshuaitao

Traceback (most recent call last):
  File "train.py", line 204, in <module>
    train(args)
  File "train.py", line 122, in train
    errD_fake = GAN_loss(output, fake_label)
  File "D:\Miniconda3\envs\mxnet\lib\site-packages\mxnet\gluon\block.py", line 542, in __call__
    out = self.forward(*args)
  File "D:\Miniconda3\envs\mxnet\lib\site-packages\mxnet\gluon\block.py", line 919, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "D:\Miniconda3\envs\mxnet\lib\site-packages\mxnet\gluon\loss.py", line 230, in hybrid_forward
    label = _reshape_like(F, label, pred)
  File "D:\Miniconda3\envs\mxnet\lib\site-packages\mxnet\gluon\loss.py", line 64, in _reshape_like
    return x.reshape(y.shape) if F is ndarray else F.reshape_like(x, y)
  File "D:\Miniconda3\envs\mxnet\lib\site-packages\mxnet\ndarray\ndarray.py", line 1062, in reshape
    ctypes.byref(handle)))
  File "D:\Miniconda3\envs\mxnet\lib\site-packages\mxnet\base.py", line 251, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:44:38] C:\Jenkins\workspace\mxnet-tag\mxnet\src\ndarray\ndarray.cc:212: Check failed: shape_.Size() >= shape.Size() (3844 vs. 4489) NDArray.Reshape: target shape size is larger current shape

**Comment by zhangshuaitao** [comment]
@havefun007，
Can you provide your training command code and which parameter to modify?

**Comment by Fannjh** [comment]
> 
> 
> @havefun007，
> Can you provide your training command code and which parameter to modify?
@zhangshuaitao
train command: "python train.py"
arguments parse:
"
    parser = argparse.ArgumentParser(description='Hyperparams')
    parser.add_argument('--img_size', nargs='?', type=int, default=512, 
                        help='Height of the input image')
    parser.add_argument('--n_epoch', nargs='?', type=int, default=10, 
                        help='# of the epochs')
    parser.add_argument('--batch_size', nargs='?', type=int, default=1, 
                        help='Batch Size')
    parser.add_argument('--lr', nargs='?', type=float, default=0.0005, 
                        help='Learning Rate')
    parser.add_argument('--beta', nargs='?', type=float, default=0.0002, 
                        help='beta')
    parser.add_argument('--trainset_path', nargs='?', type=str, default="./example/",    
                        help='Path to train images')
    parser.add_argument('--checkpoint', default='', type=str, metavar='./checkpoint/',
                    help='path to save checkpoint (default: checkpoint)')
    parser.add_argument('--model', nargs='?', type=str, default=None,    
                        help='Path to  saved model to restart from')
    parser.add_argument('--gpu', nargs='?', type=bool, default=False, 
                        help='use_gpu')
    args = parser.parse_args()
"

**Comment by zhangshuaitao** [comment]
@havefun007 ，You can refer to the following settings,
    arguments parse:
    parser = argparse.ArgumentParser(description='Hyperparams')
    parser.add_argument('--img_size', nargs='?', type=int, default=512, 
                        help='Height of the input image')
    parser.add_argument('--n_epoch', nargs='?', type=int, default=10, 
                        help='# of the epochs')
    parser.add_argument('--batch_size', nargs='?', type=int, default=1, 
                        help='Batch Size')
    parser.add_argument('--lr', nargs='?', type=float, default=0.0005, 
                        help='Learning Rate')
    parser.add_argument('--beta', nargs='?', type=float, default=0.0002, 
                        help='beta')
    parser.add_argument('--trainset_path', nargs='?', type=str, default="./example/",    
                        help='Path to train images')
    parser.add_argument('--checkpoint', default='./checkpoint/', type=str, metavar='PATH',
                    help='path to save checkpoint (default: checkpoint)')
    parser.add_argument('--model', nargs='?', type=str, default=None,    
                        help='Path to  saved model to restart from')
    parser.add_argument('--gpu', nargs='?', type=bool, default=True, 
                        help='use_gpu')
It works in my environment. Good luck!

**Comment by Fannjh** [comment]
> 
> 
> @havefun007 ，You can refer to the following settings,
> arguments parse:
> parser = argparse.ArgumentParser(description='Hyperparams')
> parser.add_argument('--img_size', nargs='?', type=int, default=512,
> help='Height of the input image')
> parser.add_argument('--n_epoch', nargs='?', type=int, default=10,
> help='# of the epochs')
> parser.add_argument('--batch_size', nargs='?', type=int, default=1,
> help='Batch Size')
> parser.add_argument('--lr', nargs='?', type=float, default=0.0005,
> help='Learning Rate')
> parser.add_argument('--beta', nargs='?', type=float, default=0.0002,
> help='beta')
> parser.add_argument('--trainset_path', nargs='?', type=str, default="./example/",
> help='Path to train images')
> parser.add_argument('--checkpoint', default='./checkpoint/', type=str, metavar='PATH',
> help='path to save checkpoint (default: checkpoint)')
> parser.add_argument('--model', nargs='?', type=str, default=None,
> help='Path to saved model to restart from')
> parser.add_argument('--gpu', nargs='?', type=bool, default=True,
> help='use_gpu')
> It works in my environment. Good luck!

Thanks, i fix it. When i change python3 to python2, it works.

**Comment by Sanster** [comment]
https://github.com/HCIILAB/Scene-Text-Removal/blob/master/model.py#L91

```python
padding = int(np.ceil((kernel_size - 1)/2))
```

- python2: padding == 1
- python3: padding == 2
